# vim:ts=2:sw=2:et
dist: trusty

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_install:
  - composer update --dev

script:
  - cd test && wget -q https://raw.github.com/atk14/Atk14/master/src/scripts/run_unit_tests && chmod +x run_unit_tests && ./run_unit_tests
